### PR TITLE
Updated rules to specify which optimizers are allowed per benchmark

### PR DESCRIPTION
**Pull request by jonathan-cohen-nvidia**
Missing for DLRM and BERT, but those can be added later.

### CODE REVIEW

**Comment by abhinavvishnu** [comment]
Would it make sense to have similar coverage on LARS with PyT and TF frameworks, as is the case with other benchmarks?

**Comment by jonathan-cohen-nvidia** [comment]
Yes, absolutely.  For RN50, this was left blank because at the time we did the analysis, TF and PyT did not match, and we were debating which one was “correct.”  That debate should be over now so we can update the table.

**Comment by jonathan-cohen-nvidia** [comment]
Can this please be merged?  @petermattson

**Comment by jonathan-cohen-nvidia** [comment]
I would like to see this merged & then I can submit another PR with the missing entries from the table.

**Comment by petermattson** [comment]
Merged.

**Pull request merged**
