### PR TITLE
Guidelines for contributing to the references

### PR DESCRIPTION
**Pull request by johntran-nv**
Copy-paste from the google doc we reviewed and approved in the Training WG a few months ago.

### CODE REVIEW

**Comment by johntran-nv** [comment]
@petermattson  or @bitfort , could one of you review this PR now that I've worked around the git login issues I was having before?

**Comment by petermattson** [comment]
LGTM with one caveat. I'd suggest we add a rule to the reference platform that states that "The Reference Platform(s) will be reviewed and updated as part of the MLPerf benchmark roadmapping process." V100 is going to gradually become old, and other platforms will emerge. :-)

**Review by petermattson — CHANGES_REQUESTED** [review]
See my previous comment re Reference platforms, then good.

**Review by johntran-nv — COMMENTED** [review]
Agreed.  Added that statement as 1a.

**Review by petermattson — APPROVED** [review]

**Pull request merged**
