### PR TITLE
Fix some references to Training rules doc

### LINKED ISSUE #462: Fix/clean some HPC rules
Some edits are needed for hpc_training_rules.adoc.

Need to remove HPC hyperparameters table link. The HP rules are all contained within the doc.

Need to update the references to rules in training_rules.adoc, probably as section links rather than rule numbers, as suggested here by @matthew-frank: https://github.com/mlcommons/training_policies/pull/458#discussion_r679992647

There is also a reference to hpc rule 6.1 under Run Results which is now wrong. We can similarly use a section link here.

### PR DESCRIPTION
**Pull request by sparticlesteve**
Using section links rather than referring to rule numbers.

Fixes #462

### CODE REVIEW

**Comment by sparticlesteve** [comment]
@johntran-nv this is basically a docs bugfix/cleanup. Can you take a look?

**Comment by TheKanter** [comment]
Hi @bitfort and @johntran-nv can we put at top of queue for Thursday  meeting?

**Comment by johntran-nv** [comment]
Since this is only touching the hpc rules doc, I'd propose that we can merge this as long as the HPC WG approves, and we don't need Training WG approval.  Does that sound reasonable, @TheKanter ?  

If so, I can't tell if the HPC WG has discussed this one yet - have they?

**Comment by sparticlesteve** [comment]
It's not a rules change. It just changes the way our hyperlinks to Training rules are implemented. It shouldn't require any discussion.

**Comment by johntran-nv** [comment]
Good point.  I agree that it's ok to merge without discussion.  Merging now.

**Pull request merged**
