### PR TITLE
Add unet3d

### PR DESCRIPTION
**Pull request by mmarcinkiewicz**
Adding hyperparameters for Image segmentation (medical) benchmark represented by a U-Net3D model.

### CODE REVIEW

**Comment by johntran-nv** [comment]
@petermattson  could you please review or delegate?

**Comment by petermattson** [comment]
+Masoud Charkhabi <masoudc@google.com> could you please find an appropriate
person? Maybe Tao?

**Comment by johntran-nv** [comment]
@petermattson , would Mehmet be an appropriate person to review this one, since he's reviewing the unet3d code PR?  I can't assign him here, I'm guessing because he's not a member of training_policies.

**Review by mndevec — APPROVED** [review]

**Comment by mmarcinkiewicz** [comment]
@petermattson @johntran-nv 
We have approval from Mehmet. Could you please merge this?

**Pull request merged**
