### PR TITLE
Whitelist precisions and allow required scaling

### LINKED ISSUE #17: Whitelist precisions
We would like to whitelist precisions known to work via discussion group. The whitelist should probably include FP16 (including IEEE and proprietary formats), FP32, and INT16. (From 5/17 meeting)

### PR DESCRIPTION
**Pull request by petermattson**
Fixes #17 and #33

### CODE REVIEW

**Comment by christ1ne** [comment]
Can we add int8 since int8 makes sense for inference? I know the current rules is for training only, I'd like to make it future proof as well.

**Comment by TheKanter** [comment]
I think we would only want to whitelist int8 for interefence, not for training.

**Comment by psyhtest** [comment]
Back to #30, scaling can compensate (a lot) for accuracy loss due to a lower precision. Without proper formalisation, some implementations could cut corners and then hide that fact using unreasonable scaling.

**Comment by petermattson** [comment]
File moved. Recreating for new name.

**Pull request closed without merging**
