### PR TITLE
TOU: Ensure comparisons across categories are explicit.

### PR DESCRIPTION
**Pull request by DilipSequeira**

### CODE REVIEW

**Comment by petermattson** [comment]
Training results presently conflate cloud/on-prem with available. I assume the intent here is only to require disclosure of:
RDI vs. preview vs. Available 
NOT Available cloud vs. Available on-prem
Correct?

**Comment by DilipSequeira** [comment]
Correct. The intent for inference 0.5 is to clearly differentiate things which are shipping/rentable and supported from other  kinds of submissions.

**Comment by johntran-nv** [comment]
@DilipSequeira , is it ok to close this really old PR?  I believe it's covered today by https://github.com/mlcommons/policies/blob/master/RESULTS_GUIDELINES.md#comparisons-based-on-secondary-or-derived-metrics-must-be-explicit.

**Comment by DilipSequeira** [comment]
What's currently in the results guidelines that prevents company A comparing their RDI submission with company B's Available submission?

**Comment by petermattson** [comment]
You can make that comparison, you just need to make it clear you're
comparing across categories. Text from the file:

When comparing MLPerf results, you must identify any benchmark differences

When comparing results the main text, table, or figure must clearly
identify any difference in version, division, category, official or
unverified status, or chipcount. When comparing Open and Closed division
results any ways in which the Open result would not qualify as a Closed
result must be identified.

**Comment by DilipSequeira** [comment]
Thanks. Agreed it's addressed already. We can close.

**Pull request closed without merging**
