### PR TITLE
Packing rule updates

### PR DESCRIPTION
**Pull request by mrinaliyer**

### CODE REVIEW

**Comment by mrinaliyer** [comment]
@guschmue Could you advise how to get past the cla-bot? I have amended the commit with the correct email id. No avail :(

**Comment by guschmue** [comment]
So cla bot complains about
```
Found following users in PR who have not signed CLA: (Mrinal Iyer, )
```
I think you need to configure your local git use mrinaliyer

**Comment by mrinaliyer** [comment]
recheck

**Comment by mrinaliyer** [comment]
@guschmue I amended my commit with a 

`git commit --amend --author="mrinaliyer <mrinali@graphcore.ai>"`

This fails, so is there anything else I should do?

**Comment by guschmue** [comment]
recheck

**Comment by guschmue** [comment]
This looks good but something is still wrong. You can see this when you click on 'Commits' above and hover over the commit author name ... github does not detect it as github handle.
I don't see what is wrong. @sub-mod, any thought?

**Pull request closed without merging**
